// models/Group.js
const mongoose = require("mongoose");

const groupSchema = new mongoose.Schema(
  {
    name: { type: String, required: true, trim: true }, // Tên gr
    slug: { type: String, index: true, unique: true, sparse: true }, // optional readable id
    description: { type: String, default: "" }, // mô tả
    avatar: { type: String, default: "" }, // ảnh
    coverPhoto: { type: String, default: "" }, // Thêm field coverPhoto
    visibility: {
      type: String,
      enum: ["public", "private", "invite"], // trạng thái
      default: "private",
    }, // trạng thái
    tags: [String],
    emotionTags: [String],
    category: [
      {
        type: String,
        enum: [
          "all",
          "happy",
          "sad",
          "angry",
          "surprised",
          "fearful",
          "disgusted",
          "neutral",
        ],
        default: "all",
      },
    ], // thể loại
    owner: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    }, // chủ gr
    moderators: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }], // các quản trị viên
    memberCount: { type: Number, default: 0 },
    isAutoGenerated: { type: Boolean, default: false },
    autoMeta: { type: mongoose.Schema.Types.Mixed },
    active: { type: Boolean, default: true },
    reportCount: {
      type: Number,
      default: 0,
    },
    warningCount: {
      type: Number,
      default: 0,
    },
  },
  { timestamps: true }
);

groupSchema.index({ tags: 1 });
groupSchema.index({ emotionTags: 1 });
module.exports = mongoose.model("Group", groupSchema);
